from __future__ import annotations

from .cloud import Capability as C
from .cloud import ProviderProfile, ProviderRegistry, ProviderStatus as S, QuantumParadigm as P


def default_provider_registry() -> ProviderRegistry:
    """Market-aware seed registry.

    These are platform-level capabilities, not a substitute for runtime
    device discovery. Each adapter must refine capabilities from live
    provider metadata before paid execution.
    """
    return ProviderRegistry([
        ProviderProfile("ibm_quantum","IBM Quantum","IBM Quantum Platform",
            frozenset({P.GATE_MODEL}),
            frozenset({C.MID_CIRCUIT_MEASUREMENT,C.RESET,C.CLASSICAL_FEED_FORWARD,C.DYNAMIC_CIRCUITS,C.BATCH,C.SESSION,C.SIMULATOR}),
            "qiskit-ibm-runtime",("Qiskit circuit","OpenQASM 3"),S.ACTIVE,
            "https://quantum.cloud.ibm.com/",
            "Direct IBM quantum cloud; device ISA/transpilation applies."),
        ProviderProfile("aws_braket","Amazon Braket","AWS",
            frozenset({P.GATE_MODEL,P.ANALOG}),
            frozenset({C.BATCH,C.RESERVATION,C.SIMULATOR,C.ANALOG_HAMILTONIAN}),
            "amazon-braket-sdk",("Braket Circuit","AHS"),S.ACTIVE,
            "https://aws.amazon.com/braket/",
            "Aggregator: AQT, IonQ, IQM, QuEra, Rigetti; device capabilities vary."),
        ProviderProfile("azure_quantum","Azure Quantum","Microsoft Azure",
            frozenset({P.GATE_MODEL,P.ANALOG}),
            frozenset({C.SIMULATOR}),
            "azure-quantum",("provider-native","QIR where supported"),S.ACTIVE,
            "https://azure.microsoft.com/products/quantum",
            "Aggregator: IonQ, Pasqal, Quantinuum, Rigetti; target capabilities vary."),
        ProviderProfile("ionq_direct","IonQ Cloud","IonQ",
            frozenset({P.GATE_MODEL}),
            frozenset({C.BATCH,C.SIMULATOR}),
            "ionq-api / supported SDKs",("IonQ circuit",),S.ACTIVE,
            "https://ionq.com/",
            "Also accessible through Braket and Azure Quantum."),
        ProviderProfile("rigetti_qcs","Rigetti QCS","Rigetti",
            frozenset({P.GATE_MODEL}),
            frozenset({C.RESET,C.BATCH,C.PULSE_CONTROL,C.SIMULATOR}),
            "pyquil",("Quil",),S.ACTIVE,
            "https://www.rigetti.com/",
            "Also accessible through Braket and Azure Quantum."),
        ProviderProfile("dwave_leap","D-Wave Leap","D-Wave",
            frozenset({P.ANNEALING,P.HYBRID}),
            frozenset({C.QUBO_ISING,C.SIMULATOR}),
            "dwave-ocean-sdk",("QUBO","Ising","CQM/DQM/hybrid"),S.ACTIVE,
            "https://cloud.dwavesys.com/leap/",
            "Annealing/hybrid semantics; not a gate-model target."),
        ProviderProfile("iqm_resonance","IQM Resonance","IQM",
            frozenset({P.GATE_MODEL}),
            frozenset({C.PULSE_CONTROL,C.SIMULATOR,C.RESERVATION}),
            "iqm-client",("IQM circuit","Qiskit/Cirq/Qrisp adapters"),S.ACTIVE,
            "https://www.meetiqm.com/iqm-resonance",
            "Also available on Amazon Braket on selected devices."),
        ProviderProfile("quantinuum_nexus","Quantinuum Nexus","Quantinuum",
            frozenset({P.GATE_MODEL}),
            frozenset({C.MID_CIRCUIT_MEASUREMENT,C.RESET,C.CLASSICAL_FEED_FORWARD,C.BATCH,C.SIMULATOR}),
            "qnexus / pytket",("TKET circuit",),S.ACTIVE,
            "https://www.quantinuum.com/products-solutions/nexus",
            "Also accessible through Azure Quantum."),
        ProviderProfile("pasqal_cloud","Pasqal Cloud","Pasqal",
            frozenset({P.ANALOG}),
            frozenset({C.ANALOG_HAMILTONIAN,C.SIMULATOR,C.BATCH}),
            "pasqal-cloud / pulser",("Pulser Sequence",),S.ACTIVE,
            "https://www.pasqal.com/",
            "Neutral-atom execution; also accessible through Azure Quantum."),
        ProviderProfile("quera","QuEra / Bloqade","QuEra / partner clouds",
            frozenset({P.ANALOG,P.GATE_MODEL}),
            frozenset({C.ANALOG_HAMILTONIAN,C.SIMULATOR}),
            "bloqade",("Bloqade analog","Bloqade digital"),S.ACTIVE,
            "https://www.quera.com/",
            "Aquila access through Amazon Braket is a key route."),
        ProviderProfile("quandela_cloud","Quandela Cloud","Quandela",
            frozenset({P.PHOTONIC}),
            frozenset({C.PHOTONIC_FOCK,C.SIMULATOR}),
            "perceval",("Perceval photonic circuit",),S.ACTIVE,
            "https://cloud.quandela.com/",
            "Photonic modality requires dedicated lowering."),
        ProviderProfile("oqc_cloud","OQC Cloud","OQC",
            frozenset({P.GATE_MODEL}),
            frozenset({C.SIMULATOR}),
            "provider API / supported integrations",("gate circuit",),S.ACTIVE,
            "https://oqc.tech/",
            "Runtime discovery required for device-specific capabilities."),
        ProviderProfile("quantum_circuits_azure","Quantum Circuits on Azure","Microsoft Azure",
            frozenset({P.GATE_MODEL}),
            frozenset({C.MID_CIRCUIT_MEASUREMENT,C.CLASSICAL_FEED_FORWARD}),
            "azure-quantum / provider target",("provider-native",),S.PREVIEW,
            "https://azure.microsoft.com/products/quantum",
            "Microsoft documentation lists Quantum Circuits as coming soon/private preview."),
    ])
