from __future__ import annotations

from dataclasses import dataclass

SPARSITY = 4
TOTAL_ERROR = 0.01
BIAS = TOTAL_ERROR / 3.0
GAMMA = SPARSITY * (1.0 - BIAS)
TARGET_ENDPOINT = 1.0 / SPARSITY
AMPLIFICATION_ERROR_BUDGET = TOTAL_ERROR / 3.0
DEGREE = 81

# Odd Chebyshev coefficients c_k for P(x)=sum c_k T_k(x), k=1,3,...,81.
# Generated by a cutting-plane linear program and frozen as a reproducibility witness.
ODD_CHEBYSHEV_COEFFICIENTS = (
    0.030881297642363196, -0.08791491939931331, 0.1315482978012762,
    -0.15534707321347463, 0.15620968782542344, -0.13492238089827022,
    0.09605958244098342, -0.04721262272912075, -0.002358821815917877,
    0.043446622270873314, -0.06868778818991775, 0.07408441805715398,
    -0.05991453239754426, 0.030782880314399408, 0.00528512263050579,
    -0.0386003726182621, 0.060098475543213695, -0.06366546202995958,
    0.047922776802654596, -0.016940660476287856, -0.02045701117463559,
    0.052812210349967886, -0.06920207322615718, 0.06271479477318817,
    -0.03324862307404255, -0.011362708818102828, 0.056619291245636104,
    -0.08517957160779781, 0.08263164714847938, -0.04380396629305766,
    -0.022476874712195883, 0.09233095883455648, -0.13198378750934175,
    0.10784361398037554, -0.009570258073574051, -0.15089878795135184,
    0.23359058561238244, -0.29575896470699786, -0.7373079443195465,
    -0.1727076237662813, 0.0956605657277174,
)


def full_chebyshev_coefficients() -> tuple[float, ...]:
    coeffs = [0.0] * (DEGREE + 1)
    for index, value in enumerate(ODD_CHEBYSHEV_COEFFICIENTS):
        coeffs[2 * index + 1] = value
    return tuple(coeffs)


def chebyshev_evaluate(x: float) -> float:
    if not -1.0 <= x <= 1.0:
        raise ValueError("x must lie in [-1, 1]")
    coeffs = full_chebyshev_coefficients()
    b_kplus1 = 0.0
    b_kplus2 = 0.0
    for coefficient in reversed(coeffs[1:]):
        b_k = 2.0 * x * b_kplus1 - b_kplus2 + coefficient
        b_kplus2 = b_kplus1
        b_kplus1 = b_k
    return x * b_kplus1 - b_kplus2 + coeffs[0]


def target(x: float) -> float:
    return GAMMA * x


@dataclass(frozen=True)
class GridCertificate:
    global_points: int
    target_points: int
    sampled_global_max_abs: float
    sampled_target_max_error: float
    sampled_odd_symmetry_residual: float
    amplification_budget: float

    @property
    def sampled_global_bound_passes(self) -> bool:
        return self.sampled_global_max_abs < 1.0

    @property
    def sampled_target_error_passes(self) -> bool:
        return self.sampled_target_max_error <= self.amplification_budget


def grid_certificate(global_points: int = 50_001, target_points: int = 25_001) -> GridCertificate:
    if global_points < 3 or target_points < 3:
        raise ValueError("grid sizes must be at least 3")

    global_max = 0.0
    odd_residual = 0.0
    for i in range(global_points):
        x = -1.0 + 2.0 * i / (global_points - 1)
        value = chebyshev_evaluate(x)
        global_max = max(global_max, abs(value))
        odd_residual = max(odd_residual, abs(value + chebyshev_evaluate(-x)))

    target_max_error = 0.0
    for i in range(target_points):
        x = -TARGET_ENDPOINT + 2.0 * TARGET_ENDPOINT * i / (target_points - 1)
        target_max_error = max(target_max_error, abs(chebyshev_evaluate(x) - target(x)))

    return GridCertificate(
        global_points=global_points,
        target_points=target_points,
        sampled_global_max_abs=global_max,
        sampled_target_max_error=target_max_error,
        sampled_odd_symmetry_residual=odd_residual,
        amplification_budget=AMPLIFICATION_ERROR_BUDGET,
    )


def batch037_certificate() -> dict[str, object]:
    cert = grid_certificate()
    return {
        "classification": "D23_EXPLICIT_NUMERICAL_POLYNOMIAL_CANDIDATE_DEGREE_81_PHASES_OPEN",
        "degree": DEGREE,
        "sparsity": SPARSITY,
        "gamma": GAMMA,
        "target_endpoint": TARGET_ENDPOINT,
        "amplification_error_budget": AMPLIFICATION_ERROR_BUDGET,
        "sampled_global_max_abs": cert.sampled_global_max_abs,
        "sampled_target_max_error": cert.sampled_target_max_error,
        "sampled_odd_symmetry_residual": cert.sampled_odd_symmetry_residual,
        "sampled_global_bound_passes": cert.sampled_global_bound_passes,
        "sampled_target_error_passes": cert.sampled_target_error_passes,
        "numerically_explicit_polynomial_candidate": True,
        "formal_global_boundedness_proof_closed": False,
        "qsp_phase_sequence_synthesized": False,
        "qsp_phase_sequence_independently_verified": False,
        "full_channel_repaired_D23_established": False,
        "real_qpu": False,
        "quantum_advantage_demonstrated": False,
        "gpu_npu_ram_dram_hbm_replacement_demonstrated": False,
    }
