"""Generate Cycle 061 source-bound acceptance evidence."""
import hashlib,json,os,re,subprocess,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];PROTOTYPE=ROOT/"software"/"uqpu-prototype";sys.path.insert(0,str(PROTOTYPE))
from uqpu.cycle061_delta01 import run_cycle061_fixture
MODULE=PROTOTYPE/"uqpu"/"cycle061_delta01.py";TESTS=PROTOTYPE/"tests"/"test_cycle061_delta01.py";PREREGISTRATION=ROOT/"benchmarks"/"experiments"/"cycle061-delta01-preregistered-gates.json";OUTPUT=ROOT/"benchmarks"/"results"/"cycle061-delta01-executable-acceptance.json"
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def main():
 environment=dict(os.environ);environment["PYTHONPATH"]=str(PROTOTYPE)+os.pathsep+environment.get("PYTHONPATH","");run=subprocess.run([sys.executable,"-m","unittest","discover","-s",str(PROTOTYPE/"tests"),"-p","test_cycle061_delta01.py","-v"],cwd=ROOT,env=environment,text=True,capture_output=True)
 if run.returncode:raise SystemExit(run.stdout+run.stderr)
 summary=re.search(r"Ran (\d+) tests?",run.stdout+run.stderr);compile_run=subprocess.run([sys.executable,"-m","py_compile",str(MODULE),str(TESTS),str(Path(__file__))],cwd=ROOT,env=environment)
 if compile_run.returncode or not summary:raise SystemExit("validation failed")
 source=b"Cycle 061 length-sixteen walks, v26 checkpoint chain, twenty-one-recovery, four-stage update and twenty-one-leaf source\n"
 with tempfile.TemporaryDirectory() as root:lanes=run_cycle061_fixture(source,root)
 artifact={"schema":"uqpu-cycle061-delta01-executable-acceptance-v1","cycle":"061","status":"PASS_LOCAL_FIXTURES_EXTERNAL_GATES_OPEN","lane_count":len(lanes),"branch":"research/cycle-061-delta-01-2026-10-03","base_cycle060_closeout_sha":"4c8fbea43dd39b86d118b7ef7fb4392b5f25edce","preregistration_commit_sha":"2f7687403b6f80a2da050002d0d59b81afcee466","implementation_commit_sha":"f79cfae5dd18e404676a341f50755d0be0b2b241","focused_tests_commit_sha":"e5cf488d70428ca1d5c3a36da01506a761962f6a","source_identity":{"preregistered_gates_git_blob_sha":"fcb0ecd3c1ab2c3c3335c8fe28d5c8c72386b0d5","portfolio_git_blob_sha":"27a8da9b68c6e896c67b38e9e6a49525c181dc73","implementation_git_blob_sha":"1363a69aafe0697de8b3194e9c8e7737f5a9813e","focused_tests_git_blob_sha":"7192628edc264a3ca8aaff6ce5187d3507e43c74","implementation_sha256":sha(MODULE),"focused_tests_sha256":sha(TESTS),"preregistered_gates_sha256":sha(PREREGISTRATION),"runner_sha256":sha(Path(__file__)),"typed_source_sha256":hashlib.sha256(source).hexdigest()},"lanes":lanes,"validation":{"focused_tests_passed":int(summary.group(1)),"focused_tests_failed":0,"py_compile":"PASS","acceptance_runner":"PASS"},"source_evidence":[{"title":"PKWARE APPNOTE v6.3.10 FINAL","url":"https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT","source_date":"2022-11-01","access_date":"2026-10-03","evidence_class":"PRIMARY_FORMAT_SPECIFICATION"},{"title":"Python os.replace documentation","url":"https://docs.python.org/3/library/os.html#os.replace","access_date":"2026-10-03","evidence_class":"PRIMARY_RUNTIME_DOCUMENTATION"},{"title":"Python os.fsync documentation","url":"https://docs.python.org/3/library/os.html#os.fsync","access_date":"2026-10-03","evidence_class":"PRIMARY_RUNTIME_DOCUMENTATION"}],"assumptions":["Bounded fixtures and models only.","Recovery is not crash durability.","Custody hashes are synthetic.","SCM is fiction-only."],"uncertainty":["External provider, hardware, durability, interoperability, custody, calibration, decision, economics, lineage and equivalence gates remain open."],"nonclaims":["No measured performance, commercial result, physical-law discovery or empirical SCM result."]}
 unsigned=json.dumps(artifact,sort_keys=True,separators=(",",":"),allow_nan=False).encode();artifact["payload_sha256"]=hashlib.sha256(unsigned).hexdigest();OUTPUT.write_text(json.dumps(artifact,indent=2,sort_keys=True)+"\n");print(json.dumps({"lanes":len(lanes),"focused_tests_passed":int(summary.group(1)),"payload_sha256":artifact["payload_sha256"],"output_sha256":sha(OUTPUT)},sort_keys=True))
if __name__=="__main__":main()
