"""Generate Cycle 046 source-bound acceptance evidence."""
import hashlib,json,os,re,subprocess,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];PROTOTYPE=ROOT/"software"/"uqpu-prototype";sys.path.insert(0,str(PROTOTYPE))
from uqpu.cycle046_delta01 import run_cycle046_fixture
MODULE=PROTOTYPE/"uqpu"/"cycle046_delta01.py";TESTS=PROTOTYPE/"tests"/"test_cycle046_delta01.py";OUTPUT=ROOT/"benchmarks"/"results"/"cycle046-delta01-executable-acceptance.json"
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def main():
 env=dict(os.environ);env["PYTHONPATH"]=str(PROTOTYPE)+os.pathsep+env.get("PYTHONPATH","");run=subprocess.run([sys.executable,"-m","unittest","discover","-s",str(PROTOTYPE/"tests"),"-p","test_cycle046_delta01.py","-v"],cwd=ROOT,env=env,text=True,capture_output=True)
 if run.returncode:raise SystemExit(run.stdout+run.stderr)
 summary=re.search(r"Ran (\d+) tests?",run.stdout+run.stderr);compile_run=subprocess.run([sys.executable,"-m","py_compile",str(MODULE),str(TESTS),str(Path(__file__))],cwd=ROOT,env=env)
 if compile_run.returncode or not summary:raise SystemExit("validation failed")
 source=b"Cycle 046 multiplicity, seal-chain, six-recovery and six-leaf source\n"
 with tempfile.TemporaryDirectory() as root:lanes=run_cycle046_fixture(source,root)
 artifact={"schema":"uqpu-cycle046-delta01-executable-acceptance-v1","cycle":"046","status":"PASS_LOCAL_FIXTURES_EXTERNAL_GATES_OPEN","lane_count":len(lanes),"branch":"research/cycle-046-delta-01-2026-10-01","base_cycle045_closeout_sha":"60e862c734367c27436dfd1a81e3babb5ce33674","preregistration_commit_sha":"1e46e0a47e336391979490a08a8b47879bb44877","implementation_commit_sha":"e60b423cc85c24fd4d41ea1cb276db320280f536","focused_tests_commit_sha":"2b23b68e44db69544bd595e0d530c4f470e0a827","source_identity":{"preregistered_gates_git_blob_sha":"53c8e3ab3eaffae7962a1b579a720fa5a0a0b3bb","portfolio_git_blob_sha":"27a8da9b68c6e896c67b38e9e6a49525c181dc73","implementation_git_blob_sha":"63325e58f348643e3d6a5b9af765a7d16729639d","focused_tests_git_blob_sha":"707286111f0090dc879c84bf0596f83fa6218678","implementation_sha256":sha(MODULE),"focused_tests_sha256":sha(TESTS),"runner_sha256":sha(Path(__file__)),"typed_source_sha256":hashlib.sha256(source).hexdigest()},"lanes":lanes,"validation":{"focused_tests_passed":int(summary.group(1)),"focused_tests_failed":0,"py_compile":"PASS","acceptance_runner":"PASS"},"source_evidence":[{"title":"PKWARE APPNOTE v6.3.10 FINAL","url":"https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT","source_date":"2022-11-01","access_date":"2026-10-01","evidence_class":"PRIMARY_FORMAT_SPECIFICATION"},{"title":"Python os.replace documentation","url":"https://docs.python.org/3/library/os.html#os.replace","access_date":"2026-10-01","evidence_class":"PRIMARY_RUNTIME_DOCUMENTATION"},{"title":"Python os.fsync documentation","url":"https://docs.python.org/3/library/os.html#os.fsync","access_date":"2026-10-01","evidence_class":"PRIMARY_RUNTIME_DOCUMENTATION"}],"assumptions":["Bounded fixtures/models only.","Recovery is not crash durability.","Custody hashes are synthetic.","SCM is fiction-only."],"uncertainty":["External provider, hardware, durability, interoperability, custody, calibration, decision, lineage and equivalence gates remain open."],"nonclaims":["No measured performance, commercial result, physical-law discovery or empirical SCM result."]}
 unsigned=json.dumps(artifact,sort_keys=True,separators=(",",":"),allow_nan=False).encode();artifact["payload_sha256"]=hashlib.sha256(unsigned).hexdigest();OUTPUT.write_text(json.dumps(artifact,indent=2,sort_keys=True)+"\n");print(json.dumps({"lanes":len(lanes),"focused_tests_passed":int(summary.group(1)),"payload_sha256":artifact["payload_sha256"],"output_sha256":sha(OUTPUT)},sort_keys=True))
if __name__=="__main__":main()
