"""Generate Cycle 059 source-bound acceptance evidence."""
import hashlib,json,os,re,subprocess,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];PROTOTYPE=ROOT/"software"/"uqpu-prototype";sys.path.insert(0,str(PROTOTYPE))
from uqpu.cycle059_delta01 import run_cycle059_fixture
MODULE=PROTOTYPE/"uqpu"/"cycle059_delta01.py";TESTS=PROTOTYPE/"tests"/"test_cycle059_delta01.py";PREREGISTRATION=ROOT/"benchmarks"/"experiments"/"cycle059-delta01-preregistered-gates.json";OUTPUT=ROOT/"benchmarks"/"results"/"cycle059-delta01-executable-acceptance.json"
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def main():
 environment=dict(os.environ);environment["PYTHONPATH"]=str(PROTOTYPE)+os.pathsep+environment.get("PYTHONPATH","");run=subprocess.run([sys.executable,"-m","unittest","discover","-s",str(PROTOTYPE/"tests"),"-p","test_cycle059_delta01.py","-v"],cwd=ROOT,env=environment,text=True,capture_output=True)
 if run.returncode:raise SystemExit(run.stdout+run.stderr)
 summary=re.search(r"Ran (\d+) tests?",run.stdout+run.stderr);compile_run=subprocess.run([sys.executable,"-m","py_compile",str(MODULE),str(TESTS),str(Path(__file__))],cwd=ROOT,env=environment)
 if compile_run.returncode or not summary:raise SystemExit("validation failed")
 source=b"Cycle 059 length-fourteen walks, v24 checkpoint chain, nineteen-recovery, staged Woodbury and nineteen-leaf source\n"
 with tempfile.TemporaryDirectory() as root:lanes=run_cycle059_fixture(source,root)
 artifact={"schema":"uqpu-cycle059-delta01-executable-acceptance-v1","cycle":"059","status":"PASS_LOCAL_FIXTURES_EXTERNAL_GATES_OPEN","lane_count":len(lanes),"branch":"research/cycle-059-delta-01-2026-10-03","base_cycle058_closeout_sha":"3224a69ed7291e49c6b59a981e5bc06d28b9717c","preregistration_commit_sha":"294e608ebf6cd7ba10610938deb85514211d98c3","implementation_commit_sha":"be9ee77f4a4a4e44bf8b29cff97b4400c87cdb4c","focused_tests_commit_sha":"16a847b0f608db7abe9dc5fa9555d417f419cb59","source_identity":{"preregistered_gates_git_blob_sha":"3f127ee0ad337b6bf323654a96b08d929fb1435c","portfolio_git_blob_sha":"27a8da9b68c6e896c67b38e9e6a49525c181dc73","implementation_git_blob_sha":"4eee08bbae5ebbc01a75827f22c80cb5c1c74fb7","focused_tests_git_blob_sha":"0d2f428c2fac2c776a5b53a27e743c6a1c48e0e1","implementation_sha256":sha(MODULE),"focused_tests_sha256":sha(TESTS),"preregistered_gates_sha256":sha(PREREGISTRATION),"runner_sha256":sha(Path(__file__)),"typed_source_sha256":hashlib.sha256(source).hexdigest()},"lanes":lanes,"validation":{"focused_tests_passed":int(summary.group(1)),"focused_tests_failed":0,"py_compile":"PASS","acceptance_runner":"PASS"},"source_evidence":[{"title":"PKWARE APPNOTE v6.3.10 FINAL","url":"https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT","source_date":"2022-11-01","access_date":"2026-10-03","evidence_class":"PRIMARY_FORMAT_SPECIFICATION"},{"title":"Python os.replace documentation","url":"https://docs.python.org/3/library/os.html#os.replace","access_date":"2026-10-03","evidence_class":"PRIMARY_RUNTIME_DOCUMENTATION"},{"title":"Python os.fsync documentation","url":"https://docs.python.org/3/library/os.html#os.fsync","access_date":"2026-10-03","evidence_class":"PRIMARY_RUNTIME_DOCUMENTATION"}],"assumptions":["Bounded fixtures and models only.","Recovery is not crash durability.","Custody hashes are synthetic.","SCM is fiction-only."],"uncertainty":["External provider, hardware, durability, interoperability, custody, calibration, decision, economics, lineage and equivalence gates remain open."],"nonclaims":["No measured performance, commercial result, physical-law discovery or empirical SCM result."]}
 unsigned=json.dumps(artifact,sort_keys=True,separators=(",",":"),allow_nan=False).encode();artifact["payload_sha256"]=hashlib.sha256(unsigned).hexdigest();OUTPUT.write_text(json.dumps(artifact,indent=2,sort_keys=True)+"\n");print(json.dumps({"lanes":len(lanes),"focused_tests_passed":int(summary.group(1)),"payload_sha256":artifact["payload_sha256"],"output_sha256":sha(OUTPUT)},sort_keys=True))
if __name__=="__main__":main()
